apiVersion: v1
kind: ConfigMap
metadata:
  namespace: logging
  name: elasticsearch-master-config
  labels:
    app: elasticsearch
    role: master
data:
  elasticsearch.yml: |-
    cluster.name: Cluster
    network.host: 0.0.0.0
    path.repo: ["/usr/share/elasticsearch/backup"]
